---

ansible_host: "{{ vault_ansible_host }}"

questionnaire_bot_instances:
  - port: 9023
    nextcloud_login: "{{ vault_questionnaire_bot_default_nextcloud_login }}"
    nextcloud_password: "{{ vault_questionnaire_bot_default_nextcloud_password }}"
    nextcloud_url: "{{ vault_questionnaire_bot_default_nextcloud_url }}"
    nextcloud_deck_index: 25
    working_directory: "/opt/questionnaire-bot/instances/9023"
    telegram_token: "{{ vault_questionnaire_bot_9023_telegram_token }}"
    telegram_admin_id: "{{ vault_questionnaire_bot_9023_telegram_admin_id }}"
    quest_container_path: "/app/questions/ref-9023.csv"
    enabled: yes
    container_name: "help_refugees_Krasnodar_bot"
  - port: 9025
    nextcloud_login: "{{ vault_questionnaire_bot_default_nextcloud_login }}"
    nextcloud_password: "{{ vault_questionnaire_bot_default_nextcloud_password }}"
    nextcloud_url: "{{ vault_questionnaire_bot_default_nextcloud_url }}"
    nextcloud_deck_index: 4
    working_directory: "/opt/questionnaire-bot/instances/9025"
    telegram_token: "{{ vault_questionnaire_bot_9025_telegram_token }}"
    telegram_admin_id: "{{ vault_questionnaire_bot_9025_telegram_admin_id }}"
    quest_container_path: "/app/questions/ref-9025.csv"
    enabled: no
    container_name: "help_refugees_vladivostok_bot"
  - port: 9031
    nextcloud_login: "{{ vault_questionnaire_bot_default_nextcloud_login }}"
    nextcloud_password: "{{ vault_questionnaire_bot_default_nextcloud_password }}"
    nextcloud_url: "{{ vault_questionnaire_bot_default_nextcloud_url }}"
    nextcloud_deck_index: 6
    working_directory: "/opt/questionnaire-bot/instances/9031"
    telegram_token: "{{ vault_questionnaire_bot_9031_telegram_token }}"
    telegram_admin_id: "{{ vault_questionnaire_bot_9031_telegram_admin_id }}"
    quest_container_path: "/app/questions/ref-9031.csv"
    memory_limit: "256M"
    cpus_limit: "0.75"
    enabled: yes
    container_name: "help_refugees_bot"
  - port: 9231
    nextcloud_login: "{{ vault_questionnaire_bot_default_nextcloud_login }}"
    nextcloud_password: "{{ vault_questionnaire_bot_default_nextcloud_password }}"
    nextcloud_url: "{{ vault_questionnaire_bot_default_nextcloud_url }}"
    nextcloud_deck_index: 20
    working_directory: "/opt/questionnaire-bot/instances/9231"
    telegram_token: "{{ vault_questionnaire_bot_9231_telegram_token }}"
    telegram_admin_id: "{{ vault_questionnaire_bot_9231_telegram_admin_id }}"
    quest_container_path: "/app/questions/ref-9231-oskol.csv"
    enabled: yes
    container_name: "help_refugees_StariyOskol_bot"
  - port: 9036
    nextcloud_login: "{{ vault_questionnaire_bot_default_nextcloud_login }}"
    nextcloud_password: "{{ vault_questionnaire_bot_default_nextcloud_password }}"
    nextcloud_url: "{{ vault_questionnaire_bot_default_nextcloud_url }}"
    nextcloud_deck_index: 26
    working_directory: "/opt/questionnaire-bot/instances/9036"
    telegram_token: "{{ vault_questionnaire_bot_9036_telegram_token }}"
    telegram_admin_id: "{{ vault_questionnaire_bot_9036_telegram_admin_id }}"
    quest_container_path: "/app/questions/ref-9036.csv"
    enabled: yes
    container_name: "help_refugees_voronezh_bot"
  - port: 9261
    nextcloud_login: "{{ vault_questionnaire_bot_default_nextcloud_login }}"
    nextcloud_password: "{{ vault_questionnaire_bot_default_nextcloud_password }}"
    nextcloud_url: "{{ vault_questionnaire_bot_default_nextcloud_url }}"
    nextcloud_deck_index: 24
    working_directory: "/opt/questionnaire-bot/instances/9261"
    telegram_token: "{{ vault_questionnaire_bot_9261_telegram_token }}"
    telegram_admin_id: "{{ vault_questionnaire_bot_9261_telegram_admin_id }}"
    quest_container_path: "/app/questions/ref-9261-shahti.csv"
    enabled: yes
    container_name: "help_refugees_Shahti_bot"
  - port: 9082
    nextcloud_login: "{{ vault_questionnaire_bot_default_nextcloud_login }}"
    nextcloud_password: "{{ vault_questionnaire_bot_default_nextcloud_password }}"
    nextcloud_url: "{{ vault_questionnaire_bot_default_nextcloud_url }}"
    nextcloud_deck_index: 23
    working_directory: "/opt/questionnaire-bot/instances/9082"
    telegram_token: "{{ vault_questionnaire_bot_9082_telegram_token }}"
    telegram_admin_id: "{{ vault_questionnaire_bot_9082_telegram_admin_id }}"
    quest_container_path: "/app/questions/ref-9082.csv"
    enabled: yes
    container_name: "help_refugees_KrimYalta_bot"
  - port: 9125
    nextcloud_login: "{{ vault_questionnaire_bot_default_nextcloud_login }}"
    nextcloud_password: "{{ vault_questionnaire_bot_default_nextcloud_password }}"
    nextcloud_url: "{{ vault_questionnaire_bot_default_nextcloud_url }}"
    nextcloud_deck_index: 4
    working_directory: "/opt/questionnaire-bot/instances/9125"
    telegram_token: "{{ vault_questionnaire_bot_9125_telegram_token }}"
    telegram_admin_id: "{{ vault_questionnaire_bot_9125_telegram_admin_id }}"
    quest_container_path: "/app/questions/vol-9125.csv"
    enabled: no
    container_name: "volunteers_vladivostok_bot"
  - port: 9131
    nextcloud_login: "{{ vault_questionnaire_bot_default_nextcloud_login }}"
    nextcloud_password: "{{ vault_questionnaire_bot_default_nextcloud_password }}"
    nextcloud_url: "{{ vault_questionnaire_bot_default_nextcloud_url }}"
    nextcloud_deck_index: 18
    working_directory: "/opt/questionnaire-bot/instances/9131"
    telegram_token: "{{ vault_questionnaire_bot_9131_telegram_token }}"
    telegram_admin_id: "{{ vault_questionnaire_bot_9131_telegram_admin_id }}"
    quest_container_path: "/app/questions/vol-9131.csv"
    memory_limit: "256M"
    cpus_limit: "0.75"
    enabled: yes
    container_name: "volunteers_31_bot"
  - port: 9331
    nextcloud_login: "{{ vault_questionnaire_bot_default_nextcloud_login }}"
    nextcloud_password: "{{ vault_questionnaire_bot_default_nextcloud_password }}"
    nextcloud_url: "{{ vault_questionnaire_bot_default_nextcloud_url }}"
    nextcloud_deck_index: 20
    working_directory: "/opt/questionnaire-bot/instances/9331"
    telegram_token: "{{ vault_questionnaire_bot_9331_telegram_token }}"
    telegram_admin_id: "{{ vault_questionnaire_bot_9331_telegram_admin_id }}"
    quest_container_path: "/app/questions/vol-9331-oskol.csv"
    enabled: yes
    container_name: "volunteers_StariyOskol_bot"
  - port: 9136
    nextcloud_login: "{{ vault_questionnaire_bot_default_nextcloud_login }}"
    nextcloud_password: "{{ vault_questionnaire_bot_default_nextcloud_password }}"
    nextcloud_url: "{{ vault_questionnaire_bot_default_nextcloud_url }}"
    nextcloud_deck_index: 4
    working_directory: "/opt/questionnaire-bot/instances/9136"
    telegram_token: "{{ vault_questionnaire_bot_9136_telegram_token }}"
    telegram_admin_id: "{{ vault_questionnaire_bot_9136_telegram_admin_id }}"
    quest_container_path: "/app/questions/vol-9136.csv"
    enabled: yes
    container_name: "volunteers_voronezh_bot"
  - port: 9182
    nextcloud_login: "{{ vault_questionnaire_bot_default_nextcloud_login }}"
    nextcloud_password: "{{ vault_questionnaire_bot_default_nextcloud_password }}"
    nextcloud_url: "{{ vault_questionnaire_bot_default_nextcloud_url }}"
    nextcloud_deck_index: 23
    working_directory: "/opt/questionnaire-bot/instances/9182"
    telegram_token: "{{ vault_questionnaire_bot_9182_telegram_token }}"
    telegram_admin_id: "{{ vault_questionnaire_bot_9182_telegram_admin_id }}"
    quest_container_path: "/app/questions/vol-9182.csv"
    enabled: yes
    container_name: "volunteers_KrimYalta_bot"
  - port: 9431
    nextcloud_login: "{{ vault_questionnaire_bot_default_nextcloud_login }}"
    nextcloud_password: "{{ vault_questionnaire_bot_default_nextcloud_password }}"
    nextcloud_url: "{{ vault_questionnaire_bot_default_nextcloud_url }}"
    nextcloud_deck_index: 19
    working_directory: "/opt/questionnaire-bot/instances/9431"
    telegram_token: "{{ vault_questionnaire_bot_9431_telegram_token }}"
    telegram_admin_id: "{{ vault_questionnaire_bot_9431_telegram_admin_id }}"
    quest_container_path: "/app/questions/ref-9431.csv"
    enabled: yes
    container_name: "help_refugees_school31_bot"
  - port: 9531
    nextcloud_login: "{{ vault_questionnaire_bot_default_nextcloud_login }}"
    nextcloud_password: "{{ vault_questionnaire_bot_default_nextcloud_password }}"
    nextcloud_url: "{{ vault_questionnaire_bot_default_nextcloud_url }}"
    nextcloud_deck_index: 21
    working_directory: "/opt/questionnaire-bot/instances/9531"
    telegram_token: "{{ vault_questionnaire_bot_9531_telegram_token }}"
    telegram_admin_id: "{{ vault_questionnaire_bot_9531_telegram_admin_id }}"
    quest_container_path: "/app/questions/ref-9531-oskol.csv"
    enabled: yes
    container_name: "school_StariyOskol_bot"
  - port: 9278
    nextcloud_login: "{{ vault_questionnaire_bot_default_nextcloud_login }}"
    nextcloud_password: "{{ vault_questionnaire_bot_default_nextcloud_password }}"
    nextcloud_url: "{{ vault_questionnaire_bot_default_nextcloud_url }}"
    nextcloud_deck_index: 22
    working_directory: "/opt/questionnaire-bot/instances/9278"
    telegram_token: "{{ vault_questionnaire_bot_9278_telegram_token }}"
    telegram_admin_id: "{{ vault_questionnaire_bot_9278_telegram_admin_id }}"
    quest_container_path: "/app/questions/ref-9278.csv"
    enabled: yes
    container_name: "school_spb_bot"
  - port: 9378
    nextcloud_login: "{{ vault_questionnaire_bot_default_nextcloud_login }}"
    nextcloud_password: "{{ vault_questionnaire_bot_default_nextcloud_password }}"
    nextcloud_url: "{{ vault_questionnaire_bot_default_nextcloud_url }}"
    nextcloud_deck_index: 22
    working_directory: "/opt/questionnaire-bot/instances/9378"
    telegram_token: "{{ vault_questionnaire_bot_9378_telegram_token }}"
    telegram_admin_id: "{{ vault_questionnaire_bot_9378_telegram_admin_id }}"
    quest_container_path: "/app/questions/school-revisited.csv"
    enabled: yes
    container_name: "small_school_spb_bot"
  - port: 9478
    nextcloud_login: "{{ vault_questionnaire_bot_default_nextcloud_login }}"
    nextcloud_password: "{{ vault_questionnaire_bot_default_nextcloud_password }}"
    nextcloud_url: "{{ vault_questionnaire_bot_default_nextcloud_url }}"
    nextcloud_deck_index: 31
    working_directory: "/opt/questionnaire-bot/instances/9478"
    telegram_token: "{{ vault_questionnaire_bot_9478_telegram_token }}"
    telegram_admin_id: "{{ vault_questionnaire_bot_9478_telegram_admin_id }}"
    quest_container_path: "/app/questions/ref-9478.csv"
    enabled: yes
    container_name: "mirsklad_ref_questionnaire_bot"
